export const SIGN_IN_USER_SUCCESS = "AUTH/SIGN_IN_USER_SUCCESS";
export const SET_SIGN_IN_MESSAGE = "AUTH/SET_SIGN_IN_MESSAGE";

export const SIGN_UP_USER_SUCCESS = "AUTH/SIGN_UP_USER_SUCCESS";
export const SET_SIGN_UP_MESSAGE = "AUTH/SET_SIGN_UP_MESSAGE";

export const RESET_USER_SUCCESS = "AUTH/RESET_USER_SUCCESS";
export const SET_RESET_MESSAGE = "AUTH/SET_RESET_MESSAGE";

export const AUTH_LISTENER = "AUTH/AUTH_LISTENER";
export const AUTH_LISTENER_ERROR = "AUTH/AUTH_LISTENER_ERROR";
export const AUTH_LISTENER_SUCCESS = "AUTH/AUTH_LISTENER_SUCCESS";

export const SET_USER_AUTHENTICATED = "AUTH/SET_USER_AUTHENTICATED";
export const SET_USER_DE_AUTHENTICATED = "AUTH/SET_USER_DE_AUTHENTICATED";

export const START_LOADING = "AUTH/START_LOADING";



