export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const AUTH_LISTENER = "AUTH_LISTENER";
export const AUTH_LISTENER_ERROR = "AUTH_LISTENER_ERROR";
export const AUTH_LISTENER_SUCCESS = "AUTH_LISTENER_SUCCESS";
export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const SET_USER_DE_AUTHENTICATED = "SET_USER_DE_AUTHENTICATED";
export const SET_SIGN_IN_ERROR_MESSAGE = "SET_SIGN_IN_ERROR_MESSAGE";
export const SET_SIGN_UP_ERROR_MESSAGE = "SET_SIGN_UP_ERROR_MESSAGE";



