export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";
export const AUTH_LISTENER = "AUTH_LISTENER";
export const AUTH_LISTENER_ERROR = "AUTH_LISTENER_ERROR";
export const AUTH_LISTENER_SUCCESS = "AUTH_LISTENER_SUCCESS";
export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const SET_USER_DE_AUTHENTICATED = "SET_USER_DE_AUTHENTICATED";
export const SET_SIGN_IN_MESSAGE = "SET_SIGN_IN_MESSAGE";
export const SET_SIGN_UP_MESSAGE = "SET_SIGN_UP_MESSAGE";
export const SET_RESET_MESSAGE = "SET_RESET_MESSAGE";
export const START_LOADING = "START_LOADING";



