export const GET_NOTES_SUCCESS = "NOTEPAD/GET_NOTES_SUCCESS";

export const SELECT_NOTE = "NOTEPAD/SELECT_NOTE";

export const UPDATE_NOTE = "NOTEPAD/UPDATE_NOTE";
export const UPDATE_NOTE_TITLE = "NOTEPAD/UPDATE_NOTE_TITLE";
export const UPDATE_NOTE_BODY = "NOTEPAD/UPDATE_NOTE_BODY";

export const DELETE_NOTE = "NOTEPAD/DELETE_NOTE";
export const DELETE_NOTE_SUCCESS = "NOTEPAD/DELETE_NOTE_SUCCESS";

export const NEW_NOTE = "NOTEPAD/NEW_NOTE";
export const NEW_NOTE_SUCCESS = "NOTEPAD/NEW_NOTE_SUCCESS";