export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";

export const SELECT_NOTE = "SELECT_NOTE";

export const UPDATE_NOTE = "UPDATE_NOTE";
export const UPDATE_NOTE_TITLE = "UPDATE_NOTE_TITLE";
export const UPDATE_NOTE_BODY = "UPDATE_NOTE_BODY";

export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";

export const NEW_NOTE = "NEW_NOTE";
export const NEW_NOTE_SUCCESS = "NEW_NOTE_SUCCESS";