export const UPDATE_PROFILE_SUCCESS = "PROFILE/UPDATE_PROFILE_SUCCESS";

export const SET_PROFILE_MESSAGE = "PROFILE/SET_PROFILE_MESSAGE";
export const CLEAR_PROFILE_MESSAGE = "PROFILE/CLEAR_PROFILE_MESSAGE";

export const UPDATE_USER_TO_USERS_SUCCESS = "PROFILE/UPDATE_USER_TO_USERS_SUCCESS";

export const START_LOADING = "PROFILE/START_LOADING";
export const STOP_LOADING = "PROFILE/STOP_LOADING";