export const UPDATE_PROFILE_SUCCESS = "PROFILE/UPDATE_PROFILE_SUCCESS";

export const SET_PROFILE_MESSAGE = "PROFILE/SET_PROFILE_MESSAGE";
export const CLEAR_PROFILE_MESSAGE = "PROFILE/CLEAR_PROFILE_MESSAGE";

export const CHANGE_AVATAR_SUCCESS = "PROFILE/CHANGE_AVATAR_SUCCESS";

export const START_LOADING = "PROFILE/START_LOADING";